# Generated by Django 5.1.1 on 2024-09-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
    ]
